-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 20:12:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Group3project
-- -----------------------------------------------------
CREATE DATABASE `Group3project`;
USE `Group3project`;
-- -----------------------------------------------------
-- Schema Group3project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Group3project` DEFAULT CHARACTER SET utf8 ;


-- -----------------------------------------------------
-- Table `Group3project`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`UserInfo` (
  `Userid` INT NOT NULL AUTO_INCREMENT,
  `AsFaculty` VARCHAR(255) NULL DEFAULT 'No',
  `FacultyApproved` INT(1) NULL DEFAULT 0,
  `AsAdmin` VARCHAR(255) NULL DEFAULT 'No',
  `AdminApproved` INT(1) NULL DEFAULT 0,
  `FirstName` VARCHAR(255) NULL,
  `LastName` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NOT NULL,
  `ProfilePic` VARCHAR(255) NULL,
  `Street` VARCHAR(255) NULL,
  `City` VARCHAR(255) NULL,
  `Zipcode` VARCHAR(255) NULL,
  `Country` VARCHAR(255) NULL,
  PRIMARY KEY (`Userid`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`UserContact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`UserContact` (
  `Userid` INT NOT NULL,
  `Phone` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Userid`, `Phone`),
  CONSTRAINT `UserId`
    FOREIGN KEY (`Userid`)
    REFERENCES `Group3project`.`UserInfo` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `Group3project`.`Passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`UserPasswords` (
  `Userid` INT NOT NULL,
  `Salt` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Userid`),
  UNIQUE INDEX `Salt_UNIQUE` (`Salt` ASC),
  CONSTRAINT `UserId_2`
    FOREIGN KEY (`Userid`)
    REFERENCES `Group3project`.`UserInfo` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Group3project`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Administrator` (
  `AdminId` INT NOT NULL,
  `GrantorId` INT NULL,
  `ApprovalDatetime` DATETIME NULL,
  PRIMARY KEY (`AdminId`),
  INDEX `GrantorId_2` (`GrantorId` ASC),
  CONSTRAINT `GrantorId`
    FOREIGN KEY (`GrantorId`)
    REFERENCES `Group3project`.`Administrator` (`AdminId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AdminId`
    FOREIGN KEY (`AdminId`)
    REFERENCES `Group3project`.`UserInfo` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Group3project`.`Topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Topics` (
  `TopicNames` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`TopicNames`),
  UNIQUE INDEX `Name_UNIQUE` (`TopicNames` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`CourseInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`CourseInfo` (
  `CourseId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `PrimaryTopic` VARCHAR(255) NOT NULL,
  `Icon` VARCHAR(255) NULL,
  `Cost` FLOAT NULL,
  `CreationDateTime` DATETIME NULL,
  PRIMARY KEY (`CourseId`),
  CONSTRAINT `Primaryt`
    FOREIGN KEY (`PrimaryTopic`)
    REFERENCES `Group3project`.`Topics` (`TopicNames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Student-Interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Student-Interest` (
  `StudentId` INT NOT NULL,
  `CourseId` INT NOT NULL,
  INDEX `StudentId_idx` (`StudentId` ASC),
  INDEX `CourseId_idx` (`CourseId` ASC),
  PRIMARY KEY (`StudentId`, `CourseId`),
  CONSTRAINT `StudentId`
    FOREIGN KEY (`StudentId`)
    REFERENCES `Group3project`.`UserInfo` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CourseId`
    FOREIGN KEY (`CourseId`)
    REFERENCES `Group3project`.`CourseInfo` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Course-Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Course-Students` (
  `CourseId` INT NOT NULL,
  `StudentId` INT NOT NULL,
  `PaymentDateTime` DATETIME NOT NULL,
  `AmountPaid` INT NOT NULL,
  `ConfirmationCode` VARCHAR(255) NOT NULL,
  `CompletionDateTime` DATETIME NULL,
  `UserComment` VARCHAR(255) NULL,
  `UserRating` INT(1) NULL,
  `CertificateLink` VARCHAR(255) NULL,
  PRIMARY KEY (`CourseId`, `StudentId`),
  INDEX `StudentId_idx` (`StudentId` ASC),
  CONSTRAINT `StudentId_1`
    FOREIGN KEY (`StudentId`)
    REFERENCES `Group3project`.`UserInfo` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Courseid_1`
    FOREIGN KEY (`CourseId`)
    REFERENCES `Group3project`.`CourseInfo` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Faculty` (
  `FacultyId` INT NOT NULL,
  `Title` VARCHAR(255) NULL,
  `WorkWebsite` VARCHAR(255) NULL,
  `Affiliation` VARCHAR(255) NULL,
  `AuthenticatorId` INT NULL,
  `AuthenticationDateTime` DATETIME NULL,
  PRIMARY KEY (`FacultyId`),
  INDEX `AuthenticatorId_idx` (`AuthenticatorId` ASC),
  CONSTRAINT `FacultyId`
    FOREIGN KEY (`FacultyId`)
    REFERENCES `Group3project`.`UserInfo` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AuthenticatorId`
    FOREIGN KEY (`AuthenticatorId`)
    REFERENCES `Group3project`.`Administrator` (`AdminId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Course-creation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Course-creation` (
  `CourseId` INT NOT NULL,
  `CreatorId` INT NOT NULL,
  PRIMARY KEY (`CourseId`, `CreatorId`),
  INDEX `CreatorId_idx` (`CreatorId` ASC),
  CONSTRAINT `Courseid_2`
    FOREIGN KEY (`CourseId`)
    REFERENCES `Group3project`.`CourseInfo` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CreatorId_2`
    FOREIGN KEY (`CreatorId`)
    REFERENCES `Group3project`.`Faculty` (`FacultyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Group3project`.`SecondaryTopics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`SecondaryTopics` (
  `CourseId` INT NOT NULL,
  `TopicName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CourseId`, `TopicName`),
  INDEX `Topic_idx` (`TopicName` ASC),
  CONSTRAINT `CourseId_3`
    FOREIGN KEY (`CourseId`)
    REFERENCES `Group3project`.`CourseInfo` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Topic_3`
    FOREIGN KEY (`TopicName`)
    REFERENCES `Group3project`.`Topics` (`TopicNames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Course-Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Course-Material` (
  `CourseId` INT NOT NULL,
  `MaterialSeqId` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Type` VARCHAR(255) NOT NULL,
  `Materialid` INT NOT NULL AUTO_INCREMENT,
  INDEX `CourseId_idx` (`CourseId` ASC),
  PRIMARY KEY (`Materialid`),
  CONSTRAINT `CourseId_4`
    FOREIGN KEY (`CourseId`)
    REFERENCES `Group3project`.`CourseInfo` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Material-Confirmation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Material-Confirmation` (
  `Materialid` INT NOT NULL,
  `StudentId` INT NOT NULL,
  `CompletionDateTime` DATETIME NULL,
  PRIMARY KEY (`Materialid`, `StudentId`),
  INDEX `StudentId_idx` (`StudentId` ASC),
  CONSTRAINT `MaterialId_1`
    FOREIGN KEY (`Materialid`)
    REFERENCES `Group3project`.`Course-Material` (`Materialid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `StudentId_5`
    FOREIGN KEY (`StudentId`)
    REFERENCES `Group3project`.`Course-Students` (`StudentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Questions` (
  `CourseId` INT NOT NULL,
  `QuestionLineId` INT NOT NULL AUTO_INCREMENT,
  `StudentId` INT NOT NULL,
  `FacultyId` INT NOT NULL,
  `Question` VARCHAR(255) NULL,
  `VisibilityFlag` INT NULL,
  PRIMARY KEY (`QuestionLineId`),
  INDEX `StudentId_idx` (`StudentId` ASC),
  INDEX `CourseId_idx` (`CourseId` ASC),
  INDEX `FacultyId_idx` (`FacultyId` ASC),
  CONSTRAINT `StudentId_6`
    FOREIGN KEY (`StudentId`)
    REFERENCES `Group3project`.`Course-Students` (`StudentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CourseId_5`
    FOREIGN KEY (`CourseId`)
    REFERENCES `Group3project`.`Course-Students` (`CourseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FacultyId_2`
    FOREIGN KEY (`FacultyId`)
    REFERENCES `Group3project`.`Course-creation` (`CreatorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Links` (
  `Materialid` INT NOT NULL,
  `URL` VARCHAR(255) NULL,
  `VideoTag` VARCHAR(255) NULL,
  PRIMARY KEY (`Materialid`),
  CONSTRAINT `MaterialId_3`
    FOREIGN KEY (`Materialid`)
    REFERENCES `Group3project`.`Course-Material` (`Materialid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Posts` (
  `Materialid` INT NOT NULL,
  `Text` VARCHAR(255) NULL,
  PRIMARY KEY (`Materialid`),
  CONSTRAINT `MaterialId_4`
    FOREIGN KEY (`Materialid`)
    REFERENCES `Group3project`.`Course-Material` (`Materialid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`DownloadableFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`DownloadableFiles` (
  `Materialid` INT NOT NULL,
  `Path` VARCHAR(255) NULL,
  `Size` VARCHAR(255) NULL,
  `Type` VARCHAR(255) NULL,
  PRIMARY KEY (`Materialid`),
  CONSTRAINT `MaterialId_5`
    FOREIGN KEY (`Materialid`)
    REFERENCES `Group3project`.`Course-Material` (`Materialid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`Course-Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`Course-Questions` (
  `Materialid` INT NOT NULL,
  `QuestionLineId` INT NOT NULL,
  PRIMARY KEY (`Materialid`, `QuestionLineId`),
  INDEX `QuestionId_idx` (`QuestionLineId` ASC),
  CONSTRAINT `MaterialId_6`
    FOREIGN KEY (`Materialid`)
    REFERENCES `Group3project`.`Course-Material` (`Materialid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `QuestionId_1`
    FOREIGN KEY (`QuestionLineId`)
    REFERENCES `Group3project`.`Questions` (`QuestionLineId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Group3project`.`QuestionRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group3project`.`QuestionRating` (
  `QuestionLineId` INT NOT NULL,
  `LikedById` INT NOT NULL,
  PRIMARY KEY (`QuestionLineId`, `LikedById`),
  INDEX `LikedById_idx` (`LikedById` ASC),
  CONSTRAINT `QuestionLineId_2`
    FOREIGN KEY (`QuestionLineId`)
    REFERENCES `Group3project`.`Questions` (`QuestionLineId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LikedById_2`
    FOREIGN KEY (`LikedById`)
    REFERENCES `Group3project`.`Course-Students` (`StudentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



