USE GROUP3project;
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (1,'No',0,'No',0,'Sabra','Huf','Huf@gmail.com','http://writingexercises.co.uk/random-images.php','4605 Ray Court','Wrightsville',28480,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (2,'No',0,'No',0,'Abigail ','Red','Red@gmail.com','http://writingexercises.co.uk/random-images.php','4516 Crestview Terrace','JAMESTOWN',49427,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (3,'No',0,'No',0,'Tresa ','Bourbeau','Bourbeau@gmail.com','http://writingexercises.co.uk/random-images.php','2539 Traders Alley','Lee S Summit',64063,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (4,'No',0,'No',0,'Micheal','Pablo','Pablo@gmail.com','http://writingexercises.co.uk/random-images.php','383 Larry Street','New Berlin',53151,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (5,'No',0,'No',0,'Deane ','Zaragosa','Zaragosa@gmail.com','http://writingexercises.co.uk/random-images.php','4758 Benedum Drive','Middletown',10940,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (6,'No',0,'No',0,'Catharine  ','Balding ','Balding@gmail.com','http://writingexercises.co.uk/random-images.php','4549 Pride Avenue','Jamaica',11432,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (7,'No',0,'No',0,'Esmeralda ','Bones','Bones@gmail.com','http://writingexercises.co.uk/random-images.php','2688 Bolman Court','Martinsville',62442,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (8,'No',0,'No',0,'Fern  ','Wormley','Wormley@gmail.com','http://writingexercises.co.uk/random-images.php','3779 Bloomfield Way','New Vineyard',14956,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (9,'No',0,'No',0,'Julius ','Syverson','Syverson@gmail.com','http://writingexercises.co.uk/random-images.php','575 Hillview Street','Columbia',30202,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (10,'No',0,'No',0,'Tracey ','Caron ','Caron@gmail.com','http://writingexercises.co.uk/random-images.php','46 Elk Creek Road','Alpharetta',30201,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (11,'No',0,'No',0,'Doloris ','Kurland','Kurland@gmail.com','http://writingexercises.co.uk/random-images.php','1920 Sunny Glen Lane','Cleveland',44114,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (12,'No',0,'No',0,'Victorina ','Watt ','Watt@gmail.com','http://writingexercises.co.uk/random-images.php','4053 Wakefield Street','Philadelphia',19107,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (13,'No',0,'No',0,'Annelle  ','Wadkins','Wadkins@gmail.com','http://writingexercises.co.uk/random-images.php','2076 Edsel Road','Los Angeles',90017,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (14,'No',0,'No',0,'Yan ','Nicolai ','Nicolai@gmail.com','http://writingexercises.co.uk/random-images.php','1661 Jones Street','Fort Worth',76105,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (15,'No',0,'No',0,'Saundra  ','Morton','Morton@gmail.com','http://writingexercises.co.uk/random-images.php','1275 Lauren Drive','Merrimac',53561,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (16,'No',0,'No',0,'Chuck ','Kittle','Kittle@gmail.com','http://writingexercises.co.uk/random-images.php','3418 Peaceful Lane','Warrensville Heights',44128,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (17,'No',0,'No',0,'Henriette','Hitch','Hitch@gmail.com','http://writingexercises.co.uk/random-images.php','2613 Matthews Street','Rockford',61101,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (18,'No',0,'No',0,'Christy','Gillispie','Gillispie@gmail.com','http://writingexercises.co.uk/random-images.php','3156 Old House Drive','Gallipolis',45631,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (19,'No',0,'No',0,'Ardis ','Oliphant ','Oliphant@gmail.com','http://writingexercises.co.uk/random-images.php','2126 Farland Avenue','NACOGDOCHES',75965,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (20,'No',0,'No',0,'Tamra ','Pickerel','Pickerel@gmail.com','http://writingexercises.co.uk/random-images.php','798 Big Elm','LOVELY',41231,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (21,'Yes',1,'No',0,'Magnolia','Reimann','Reimann@gmail.com','http://writingexercises.co.uk/random-images.php','3812 Poplar Street','Burr Ridge',60527,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (22,'Yes',1,'No',0,'Sheena ','Furman','Furman@gmail.com','http://writingexercises.co.uk/random-images.php','1658 Lee Avenue','Somerdale',18083,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (23,'Yes',1,'No',0,'Romaine  ','Gallardo','Gallardo@gmail.com','http://writingexercises.co.uk/random-images.php','834 Cody Ridge Road','Enid',73701,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (24,'Yes',1,'No',0,'Sylvester ','Jolicoeur','Jolicoeur@gmail.com','http://writingexercises.co.uk/random-images.php','2836 Clinton Street','Little Rock',72212,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (25,'Yes',1,'No',0,'Maximina ','Deforest ','Deforest@gmail.com','http://writingexercises.co.uk/random-images.php','2615 Delaware Avenue','San Francisco',94108,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (26,'Yes',1,'No',0,'Mariana   ','Atilano','Atilano@gmail.com','http://writingexercises.co.uk/random-images.php','2369 Frank Avenue','Pittsburgh',15205,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (27,'Yes',1,'No',0,'Reginia ','Mathew ','Mathew@gmail.com','http://writingexercises.co.uk/random-images.php','793 Romano Street','Cambridge',12141,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (28,'Yes',1,'No',0,'Fransisca ','Willcutt ','Willcutt@gmail.com','http://writingexercises.co.uk/random-images.php','2572 Hilltop Drive','Coldwater',79022,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (29,'Yes',1,'No',0,'Karole ','Mcguire','Mcguire@gmail.com','http://writingexercises.co.uk/random-images.php','4924 Waldeck Street','Arlington',76011,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (30,'Yes',1,'No',0,'Grisel ','Veneziano','Veneziano@gmail.com','http://writingexercises.co.uk/random-images.php','2001 Riverwood Drive','Redding',96001,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (31,'No',0,'Yes',1,'Vickey  ','Bivona','Bivona@gmail.com','http://writingexercises.co.uk/random-images.php','4186 Ritter Street','Birmingham',35203,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (32,'No',0,'Yes',1,'Dwayne  ','Taggert','Taggert@gmail.com','http://writingexercises.co.uk/random-images.php','4862 Sweetwood Drive','Denver',80202,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (33,'No',0,'Yes',1,'Caryl ','Mcgeorge','Mcgeorge@gmail.com','http://writingexercises.co.uk/random-images.php','2455 Maple Street','HAMER',29547,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (34,'No',0,'Yes',1,'Tyra   ','Doll','Doll@gmail.com','http://writingexercises.co.uk/random-images.php','736 Jarvisville Road','Lynbrook',11563,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (35,'No',0,'Yes',1,'Arnold ','Molinari ','Molinari@gmail.com','http://writingexercises.co.uk/random-images.php','1854 Simpson Avenue','Lewisberry',17339,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (36,'No',0,'Yes',1,'Zana ','Lorraine','Lorraine@gmail.com','http://writingexercises.co.uk/random-images.php','3520 Star Trek Drive','Port St Joe',32456,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (37,'No',0,'Yes',1,'Magdalene ','Rieger','Rieger@gmail.com','http://writingexercises.co.uk/random-images.php','2033 Jerry Dove Drive','Beaufort',29902,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (38,'No',0,'Yes',1,'Mitzie ','Oritz ','Oritz@gmail.com','http://writingexercises.co.uk/random-images.php','3587 Andell Road','Nashville',37206,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (39,'No',0,'Yes',1,'Bart ','Breunig ','Breunig@gmail.com','http://writingexercises.co.uk/random-images.php','3698 Locust Street','YORK',17406,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (40,'No',0,'Yes',1,'Verlene ','Alan','Alan@gmail.com','http://writingexercises.co.uk/random-images.php','4002 Prospect Valley Road','Gardena',90247,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (41,'Yes',0,'No',0,'Ding ','Li','Dinging@gmail.com','http://writingexercises.co.uk/random-images.php','1658 Lee Avenue','Somerdale',18083,'US');
INSERT INTO `UserInfo` (`Userid`,`AsFaculty`,`FacultyApproved`,`AsAdmin`,`AdminApproved`,`FirstName`,`LastName`,`Email`,`ProfilePic`,`Street`,`City`,`Zipcode`,`Country`) VALUES (42,'No',0,'Yes',0,'Khozem','Loki','khoji@gmail.com','http://writingexercises.co.uk/random-images.php','25 westland ave','Boston',22115,'US');


INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (1,5569699910);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (2,5569699911);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (3,5569699912);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (4,5569699913);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (5,5569699914);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (6,5569699915);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (7,5569699916);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (8,5569699917);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (9,5569699918);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (10,5569699919);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (11,5569699920);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (12,5569699921);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (13,5569699922);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (14,5569699923);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (15,5569699924);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (16,5569699925);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (17,5569699926);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (18,5569699927);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (19,5569699928);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (20,5569699929);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (21,5569699930);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (22,5569699931);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (23,5569699932);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (24,5569699933);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (25,5569699934);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (26,5569699935);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (27,5569699936);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (28,5569699937);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (29,5569699938);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (30,5569699939);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (31,5569699940);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (32,5569699941);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (33,5569699942);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (34,5569699943);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (35,5569699944);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (36,5569699945);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (37,5569699946);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (38,5569699947);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (39,5569699948);
INSERT INTO `UserContact` (`Userid`,`Phone`) VALUES (40,5569699949);

INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (1,'GD72','6DA176A34D47945E446993325D829EA7BC86988874BC2CCEAD6B5A8422A38647');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (2,'YV46','35A09B4B20D56DE01A0E8A4C5A5853D31A7E46B8DDE466218F52F7CE300A6749');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (3,'WM51','3182DC30D3ED3CCF8ADCD86BC78333367227495B13623B390847D306BBB5B824');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (4,'IH38','42C264ABBF72D4FCF28A9D6DD126B4543B44CA6871A9B8C7CDF56FCE3CD99BC1');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (5,'VF45','31A106334520D06270173A81B499162978EA2B0D30A984D8EF235A1CF94E6D61');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (6,'NU64','A06D3C007A137A999A86E88C3D6B483E6F027C9874017E5B77960F4A66625EF3');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (7,'GO30','A6FABAB4BE19D4818351EAC0034E245C823BC4E7AE7EBC1E8113DEDAEE17A151');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (8,'BJ44','95EC72923D230F7EFE2041795B2B4986F98C68BF07A718CE754B1A76B974B69D');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (9,'ZB61','DEFE25DF8C0A8DD8E083E39F725D7DD17D163E935C59D570A3D201042296BF51');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (10,'OH36','4171B5FED598E640805901D45393937F70FD733CA831720977279582DE0025CC');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (11,'BS51','1E376469F105D998335278B7529E9626A09471D77F959DE40D6780FE4843CBCB');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (12,'YK17','8E7CA5006340DA72151B5C1AC5AB8902A431B6285844AE9E27438C80A4ADE0CE');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (13,'NV85','938119F78917724742955EFF1AD291580BC4F918389D8DC8C8A9F71313766EAF');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (14,'NR13','68CE054E3B6A3C8175B8697A3A04A2ED975195551BD69BCC3881D1B09332BA16');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (15,'ZX44','871BF6F300753AA2222409795871B237B7390C743F93CF4C8B2485B4A72E47B8');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (16,'KG90','F5B6653BFFCD1F8C3AFE8CA05EBCEFB6B1197D489599B59E2F5B822D2FC035BA');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (17,'XS56','4BAB0E7BEB7BCD018ABB68303ED6B212D7327A7CF13F07F95055ACB1DD0790E6');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (18,'DQ29','B0D9864E431E92F22A47118D9F30C044DA3A553F75813B08FB9504BB58E4159A');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (19,'CO93','75BD7B50B46EC6F650200B1BF094395CBD927AF5ED6C3E22B8C8E5DDA4DE076F');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (20,'PP93','1AEDF7D11A6D0A276A59189629F931EB05CC012730B92E27E6BCE5CCD76B5707');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (21,'GZ47','9CAB6E23BF1B7F31F3A660376C265286B29B45E904EA823AF0BF31D1DB6BF825');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (22,'OM68','0AAAB84A0FE74A1590C5BDC098832025C90F6A6953BE02244A00C5EA88C7B9EB');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (23,'LG42','98000D9C8BE62242E38C040CEB06423BFBFA79DFC14438C35D6D1A852DA3ED84');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (24,'ZV57','163BDAFCB66BEFCE11C486E1184A8DCB604D17D0E7BD7F7F5890A15BA6FBBED1');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (25,'AO80','ABA0BB611D56BB191473234FE23B368DDE1D4D0140C1CE9189CAA2DE5F48BADB');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (26,'YC63','8D2BBC9CA5A7AD73AA9FA73EBA0E4E6C2CD97757EE45B3BD3FA39443440E29A4');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (27,'RP77','479B804A57188812FCE2858556E0D05DD98451525DF5E11BC725F1CFB25D0E11');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (28,'SQ30','72153685F64CECFE34F74354E977EED173F9267A7FB2403525CD2A5E062C6CE0');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (29,'IR67','DF123E10090E2F6DD59C3BE723953B5574CDFA3628B431F21F858E90CF21462E');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (30,'XB17','86C1B2CDF4160B9C9E3F9C96183B232C3F9530D00E2B6C801131EDDD6E5652F5');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (31,'AN53','AE63C7E8932D757C1099D2D5C0D3C4E7DAAD050888652FBD8274540A15C533B6');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (32,'ZC18','01D4EE64E8CD596A69C9FA730A9A4D2E41E3498C8FB5F782E68C90DF916DA46F');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (33,'GU56','44A9CECFA924D3E1E353E29B6FCE47213C612F0A95E091F0F4992E7E34A49A95');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (34,'BG79','996E93E7C8742C7684C4F498FF151D30347F25E0DC690E53A5AD20F17096D3A9');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (35,'IC21','1CDC5D4766B05D5540838F9F25C5CBB8CB050278EE0577E600FE83CFF6424557');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (36,'BN80','A6E4E13575E5F3D4D736F7F7955CC10A9D3A797F9B5CF1DFD0ACF4AA1250A5E9');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (37,'IV17','2ED2EE1072C0B25FCEA7A195B2E8DCF5D4C8D2BCC8728C954FCB1EC75C36A76D');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (38,'RZ12','22E88DF7D71CCB5A14D4AF1B043406FFCB612D753DE2116DEA43F320FD53DB70');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (39,'BK16','E32F257833D96D3B2F6FBF7DCDA94498FA1CE77B3F30878D7F6805A9A40CBDEF');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (40,'KI70','D9ABC7B4E33CFA5210A6B51BC345C236E7A88BD98CCCDB97C77D9D44C2F7B565');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (41,'K270','A5AEC6FE74AC8F11D4B01195CE83646AFEDDC226DB6864257220916628624E3B');
INSERT INTO `UserPasswords` (`Userid`,`Salt`,`Password`) VALUES (42,'K370','C7D8575A7CF0D1E905E4E3B4CBBFC35B575FBC4281DB0A15115B140B88669200');

INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (31,31,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (32,31,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (33,32,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (34,32,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (35,31,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (36,34,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (37,31,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (38,34,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (39,31,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (40,37,'2017-11-21 17:15:00');
INSERT INTO `Administrator` (`AdminId`,`GrantorId`,`ApprovalDatetime`) VALUES (42,null,null);

INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (21,'AssociateProfessor','www.snappjamie.com','NEU',31,'2004-04-22 07:00:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (22,'Professor','www.omggg.com','NEU',31,'2004-04-22 07:01:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (23,'Professor','www.snappy.com','NEU',31,'2004-04-22 07:02:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (24,'AssociateProfessor','www.gofym.com','NEU',31,'2004-04-23 07:03:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (25,'AssociateProfessor','www.rampagy.com','NEU',31,'2004-04-22 07:04:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (26,'Professor','www.littlepiggy.com','NEU',32,'2007-06-02 09:05:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (27,'AssociateProfessor','www.swsteak.com','NEU',32,'2007-06-03 09:05:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (28,'AssociateProfessor','www.pitboys.com','NEU',32,'2007-06-04 09:05:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (29,'Professor','www.bbqroast.com','NEU',32,'2007-06-05 09:05:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (30,'AssociateProfessor','www.freqfri.com','NEU',32,'2007-06-06 09:05:00');
INSERT INTO `Faculty` (`FacultyId`,`Title`,`WorkWebsite`,`Affiliation`,`AuthenticatorId`,`AuthenticationDateTime`) VALUES (41,'AssociateProfessor','www.snappjamie.com','NEU',null,null);

INSERT INTO `Topics` (`TopicNames`) VALUES ('Java');
INSERT INTO `Topics` (`TopicNames`) VALUES ('Python');
INSERT INTO `Topics` (`TopicNames`) VALUES ('Algorithms');
INSERT INTO `Topics` (`TopicNames`) VALUES ('SQL');
INSERT INTO `Topics` (`TopicNames`) VALUES ('Data');
INSERT INTO `Topics` (`TopicNames`) VALUES ('AI');
INSERT INTO `Topics` (`TopicNames`) VALUES ('PHP');
INSERT INTO `Topics` (`TopicNames`) VALUES ('MongoDB');
INSERT INTO `Topics` (`TopicNames`) VALUES ('HTML');
INSERT INTO `Topics` (`TopicNames`) VALUES ('JavaScript');


INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (1,'Complete Java Masterclass','Learn to master Java 8 and Java 9 core development step-by-step, and make your first unique, advanced program in 30 days','Java','http://writingexercises.co.uk/random-images.php',195,'2017-11-21 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (2,'Complete Python Bootcamp Go from zero to hero in Python','Learn Python like a Professional  Start from the basics and go all the way to creating your own applications and games ','Python','http://writingexercises.co.uk/random-images.php',195,'2017-11-10 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (3,'Practical Data Structures and Algorithms in Java HW','Keep it Practical  Learn in-depth the most popular Data structures and  Searching Algorithms','Algorithms','http://writingexercises.co.uk/random-images.php',150,'2017-11-05 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (4,'SQL Tutorial: Learn SQL with MySQL Database Beginner2Expert','Learn SQL and Database Development: SQL Tutorial for learning Structured Query Language using MySQL Database','SQL','http://writingexercises.co.uk/random-images.php',195,'2017-10-10 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (5,'Data Science A Z: Real Life Data Science Exercises Included','Learn Data Science step by step through real Analytics examples. Data Mining, Modeling, Tableau Visualization and more ','Data','http://writingexercises.co.uk/random-images.php',200,'2017-11-03 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (6,'Artificial Intelligence A Z Learn How To Build An AI','Combine the power of Data Science, Machine Learning and Deep Learning to create powerful AI for Real-World applications ','AI','http://writingexercises.co.uk/random-images.php',200,'2017-11-04 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (7,'PHP for Beginners Become a PHP Master CMS Project','PHP for Beginners: learn everything you need to become a professional PHP developer with practical exercises and  projects.','PHP','http://writingexercises.co.uk/random-images.php',200,'2017-11-19 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (8,'The Complete Developers Guide to MongoDB','Master MongoDB and Mongoose design with a test-driven approach','MongoDB','http://writingexercises.co.uk/random-images.php',150,'2017-11-17 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (9,'The Web Developer Bootcamp','The only course you need to learn web development - HTML, CSS, JS, Node, and More ','HTML','http://writingexercises.co.uk/random-images.php',200,'2017-11-07 00:00:00');
INSERT INTO `CourseInfo` (`CourseId`,`Name`,`Description`,`PrimaryTopic`,`Icon`,`Cost`,`CreationDateTime`) VALUES (10,'The Complete JavaScript Course Build a Real-World Project','Master JavaScript with the most complete JavaScript course on the market  Includes projects, challenges, final exam, ES6','JavaScript','http://writingexercises.co.uk/random-images.php',195,'2017-11-20 00:00:00');

INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (1,21);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (1,25);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (2,22);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (2,23);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (2,24);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (3,26);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (4,27);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (4,28);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (5,29);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (6,30);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (6,21);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (7,22);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (8,23);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (9,24);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (10,25);
INSERT INTO `Course-creation` (`CourseId`,`CreatorId`) VALUES (10,26);

INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (1,1,'Introduction','Posts',1);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (1,2,'Object oriented Programming','Links',2);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (1,3,'Data types','Posts',3);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (2,1,'Introduction','Posts',4);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (2,2,'Data Analytics','Links',5);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (2,3,'Project','DownloadableFiles',6);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (3,1,'Sorting Algorithms','Posts',7);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (3,2,'Data structures','Posts',8);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (3,3,'Complexity','Links',9);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (3,4,'Trees','Links',10);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (4,1,'Relational Database Systems','Posts',11);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (4,2,'ERD','Links',12);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (4,3,'Logical Schema','DownloadableFiles',13);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (4,4,'Nested queries','Posts',14);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (5,1,'Introduction','Posts',15);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (5,2,'R programming','Links',16);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (5,3,'Statistics','Links',17);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (5,4,'Distributions','Posts',18);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (6,1,'Introduction','Posts',19);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (6,2,'Robotics','Links',20);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (6,3,'Machine Learning','Links',21);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (7,1,'Basic Concepts','Posts',22);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (7,2,'Web programming','Links',23);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (7,3,'Database Management ','Links',24);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (7,4,'PHP Advanced','DownloadableFiles',25);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (8,1,'Database System history','Posts',26);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (8,2,'Relational Databases','Posts',27);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (8,3,'Non relational databases','Links',28);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (8,4,'MongoDB ','Links',29);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (8,5,'Advanced MongoDB','DownloadableFiles',30);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (9,1,'Introduction','Posts',31);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (9,2,'Web development Technologies','Links',32);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (9,3,'Javascript','Links',33);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (9,4,'HTML','Links',34);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (9,5,'CSS','Links',35);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (10,1,'Introduction','Posts',36);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (10,2,'Javascript A Z','Links',37);
INSERT INTO `Course-Material` (`CourseId`,`MaterialSeqId`,`Name`,`Type`,`Materialid`) VALUES (10,3,'Project','DownloadableFiles',38);


INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(1, 1, '2017-11-21 15:50:00', 195, 'bdsjbdsj', '2017-11-26 15:00:00', NULL, 3, 'mypath/certi1');
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(1, 2, '2017-11-21 15:50:00', 195, 'sdajh', '2017-12-11 00:00:00', NULL, 4, 'mypath/certi2');
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(1, 4, '2017-11-21 15:50:00', 195, 'sbdnd', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(1, 5, '2017-11-21 15:50:00', 195, 'asbjs', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(2, 1, '2017-11-21 15:50:00', 195, 'hfeub', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(2, 3, '2017-11-21 15:50:00', 195, 'sadhb', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(2, 4, '2017-11-21 15:50:00', 195, 'ewuww', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(2, 6, '2017-11-21 15:50:00', 195, 'sbdhh', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(2, 11, '2017-11-21 15:50:00', 195, 'bcdnd', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(3, 3, '2017-11-21 15:50:00', 150, 'jfbkw', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(3, 12, '2017-11-21 15:50:00', 150, ' mvdke', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(3, 14, '2017-11-21 15:50:00', 150, 'efnkn', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(3, 15, '2017-11-21 15:50:00', 150, 'ieoew', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(3, 18, '2017-11-21 15:50:00', 150, 'velep', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(3, 20, '2017-11-21 15:50:00', 150, 'ewknf', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(4, 6, '2017-11-21 15:50:00', 195, 'ejfiv', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(4, 9, '2017-11-21 15:50:00', 195, 'woqpl', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(4, 17, '2017-11-21 15:50:00', 195, 'mfrok', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(5, 19, '2017-11-21 15:50:00', 200, 'fekmo', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(6, 13, '2017-11-21 15:50:00', 200, 'qwokw', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(6, 16, '2017-11-21 15:50:00', 200, 'rlgmo', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(6, 18, '2017-11-21 15:50:00', 200, 'rekgm', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(6, 19, '2017-11-21 15:50:00', 200, 'thkmv', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(6, 20, '2017-11-21 15:50:00', 200, 'kdsfn', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(7, 1, '2017-11-21 15:50:00', 200, 'dnfjk', '2017-12-11 00:00:00', NULL, 4, 'mypath/certi4');
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(7, 2, '2017-11-21 15:50:00', 200, 'thrkp', '2017-12-11 00:00:00', NULL, 5, 'mypath/certi3');
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(7, 5, '2017-11-21 15:50:00', 200, 'nvmds', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(8, 11, '2017-11-21 15:50:00', 150, 'greko', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(8, 17, '2017-11-21 15:50:00', 150, 'kwlpq', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(9, 2, '2017-11-21 15:50:00', 200, 'qiqjq', '2017-12-11 00:00:00', NULL, 2, 'mypath/certi5');
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(9, 5, '2017-11-21 15:50:00', 200, 'oktpl', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(9, 7, '2017-11-21 15:50:00', 200, 'xNJsk', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(9, 9, '2017-11-21 15:50:00', 200, 'slmwp', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(9, 13, '2017-11-21 15:50:00', 200, 'wemda', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(9, 17, '2017-11-21 15:50:00', 200, 'regkp', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(10, 6, '2017-11-21 15:50:00', 195, 'bkslk', NULL, NULL, NULL, NULL);
INSERT INTO `Course-Students` (`CourseId`, `StudentId`, `PaymentDateTime`, `AmountPaid`, `ConfirmationCode`, `CompletionDateTime`, `UserComment`, `UserRating`, `CertificateLink`) VALUES(10, 8, '2017-11-21 15:50:00', 195, 'gbmmw', NULL, NULL, NULL, NULL);




INSERT INTO `DownloadableFiles` (`Materialid`,`Path`,`Size`,`Type`) VALUES (6,'C:\\Users\\Ravi\\Desktop\\Material\\six.xlsx','1269','xlsx');
INSERT INTO `DownloadableFiles` (`Materialid`,`Path`,`Size`,`Type`) VALUES (13,'C:\\Users\\Ravi\\Desktop\\Material\\thirteen.pdf','1300','Pdf');
INSERT INTO `DownloadableFiles` (`Materialid`,`Path`,`Size`,`Type`) VALUES (25,'C:\\Users\\Ravi\\Desktop\\Material\\twentyfive.pdf','1353','Pdf');
INSERT INTO `DownloadableFiles` (`Materialid`,`Path`,`Size`,`Type`) VALUES (38,'C:\\Users\\Ravi\\Desktop\\Material\\twentysix.xlsx','1357','xlsx');
INSERT INTO `DownloadableFiles` (`Materialid`,`Path`,`Size`,`Type`) VALUES (30,'C:\\Users\\Ravi\\Desktop\\Material\\twentythirty.xlsx','1375','xlsx');


INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (2,'https://www.youtube.com/watch?v=7Vtl2WggqOg','Yes');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (5,'http://www.freesfx.co.uk/rx2/mp3s/1/680_1233690812.mp3','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (9,'https://www.youtube.com/watch?v=1nCst3slw5k','Yes');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (10,'http://psychic3d.free.fr/extra_fichiers/sons/eau_calme.wav','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (12,'https://www.youtube.com/watch?v=uAWWhEA57bE','Yes');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (16,'http://psychic3d.free.fr/extra_fichiers/sons/eau_calme.wav','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (17,'https://www.youtube.com/watch?v=UrYLYV7WSHM','Yes');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (20,'http://chat.anthrochat.net/images/actmsg.wav','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (21,'https://www.youtube.com/watch?v=YJqkG9BV6hU','Yes');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (23,'http://jpolito.zlique.org/server/sound/player/pl_wade4.wav','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (24,'https://www.youtube.com/watch?v=XTwoPRcSpIo','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (28,'https://www.youtube.com/watch?v=kK_2mzBARTU','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (29,'https://www.youtube.com/watch?v=UB1O30fR-EE','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (32,'https://www.youtube.com/watch?v=9hDKfBKuXjI','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (33,'https://www.youtube.com/watch?v=ccCblUZFM0w','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (34,'https://www.youtube.com/watch?v=fju9ii8YsGs','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (35,'https://www.youtube.com/watch?v=O8wwnhdkPE4','No');
INSERT INTO `Links` (`Materialid`,`URL`,`VideoTag`) VALUES (37,'https://www.youtube.com/watch?v=BWXggB-T1jQ','No');

INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(1, 1, '2017-11-21 16:27:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(1, 2, '2017-11-21 16:36:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(1, 4, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(1, 5, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(2, 1, '2017-11-21 16:27:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(2, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(2, 4, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(2, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(3, 1, '2017-11-23 15:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(3, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(3, 4, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(3, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(4, 1, '2017-11-21 16:28:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(4, 3, '2017-11-21 16:37:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(4, 4, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(4, 6, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(4, 11, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(5, 1, '2017-11-21 16:28:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(5, 3, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(5, 4, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(5, 6, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(5, 11, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(6, 1, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(6, 3, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(6, 4, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(6, 6, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(6, 11, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(7, 3, '2017-11-21 16:37:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(7, 12, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(7, 14, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(7, 15, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(7, 18, '2017-11-21 16:41:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(7, 20, '2017-11-21 16:42:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(8, 3, '2017-11-21 16:37:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(8, 12, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(8, 14, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(8, 15, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(8, 18, '2017-11-21 16:41:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(8, 20, '2017-11-21 16:42:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(9, 3, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(9, 12, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(9, 14, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(9, 15, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(9, 18, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(9, 20, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(10, 3, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(10, 12, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(10, 14, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(10, 15, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(10, 18, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(10, 20, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(11, 6, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(11, 9, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(11, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(12, 6, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(12, 9, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(12, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(13, 6, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(13, 9, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(13, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(14, 6, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(14, 9, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(14, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(15, 19, '2017-11-21 16:41:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(16, 19, '2017-11-21 16:41:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(17, 19, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(18, 19, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(19, 13, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(19, 16, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(19, 18, '2017-11-21 16:41:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(19, 19, '2017-11-21 16:42:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(19, 20, '2017-11-21 16:42:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(20, 13, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(20, 16, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(20, 18, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(20, 19, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(20, 20, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(21, 13, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(21, 16, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(21, 18, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(21, 19, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(21, 20, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(22, 1, '2017-11-21 16:36:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(22, 2, '2017-11-21 16:36:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(22, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(23, 1, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(23, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(23, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(24, 1, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(24, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(24, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(25, 1, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(25, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(25, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(26, 11, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(26, 17, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(27, 11, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(27, 17, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(28, 11, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(28, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(29, 11, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(29, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(30, 11, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(30, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(31, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(31, 5, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(31, 7, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(31, 9, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(31, 13, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(31, 17, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(32, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(32, 5, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(32, 7, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(32, 9, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(32, 13, '2017-11-21 16:40:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(32, 17, '2017-11-21 16:41:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(33, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(33, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(33, 7, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(33, 9, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(33, 13, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(33, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(34, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(34, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(34, 7, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(34, 9, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(34, 13, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(34, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(35, 2, '2017-12-11 00:00:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(35, 5, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(35, 7, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(35, 9, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(35, 13, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(35, 17, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(36, 6, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(36, 8, '2017-11-21 16:39:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(37, 6, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(37, 8, NULL);
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(38, 6, '2017-11-21 16:38:00');
INSERT INTO `Material-Confirmation` (`Materialid`, `StudentId`, `CompletionDateTime`) VALUES(38, 8, NULL);




INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (1,'a general-purpose computer programming language designed to produce programs that will run on any computer system.');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (3,'Python is a general purpose programming language created in the late 1980s');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (4,'a process or set of rules to be followed in calculations or other problem-solving operations');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (7,'SQL stands for Structured Query Language. SQL is used to communicate with a database.');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (8,'the quantities being stored and transmitted in the form of electrical signals and recorded on magnetic  optical  or mechanical recording media');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (11,'Artificial intelligence is Intelligence displayed by machines');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (14,'PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (15,'MongoDB stores data in flexible, JSON-like documents, meaning fields can vary from document to document and data structure can be changed over time.');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (18,'Hypertext Markup Language is the standard markup language for creating web pages and web applications. With Cascading Style Sheets and JavaScript it forms a triad of cornerstone technologies for the World Wide Web. ');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (19,'JavaScript, often abbreviated as JS, is a high-level, dynamic, weakly typed, prototype-based, multi-paradigm, and interpreted programming language');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (22,'JavaScript, often abbreviated as JS, is a high-level, dynamic, weakly typed, prototype-based, multi-paradigm, and interpreted programming language');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (26,'JavaScript, often abbreviated as JS, is a high-level, dynamic, weakly typed, prototype-based, multi-paradigm, and interpreted programming language');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (27,'JavaScript, often abbreviated as JS, is a high-level, dynamic, weakly typed, prototype-based, multi-paradigm, and interpreted programming language');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (31,'JavaScript, often abbreviated as JS, is a high-level, dynamic, weakly typed, prototype-based, multi-paradigm, and interpreted programming language');
INSERT INTO `Posts` (`Materialid`,`Text`) VALUES (36,'JavaScript, often abbreviated as JS, is a high-level, dynamic, weakly typed, prototype-based, multi-paradigm, and interpreted programming language');


INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (1,1,2,21,'How can I make myself a master in JAVA?',0);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (9,2,5,24,'What is JAVAEE?',0);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (3,3,3,26,'How do algorithms work in JAVA?',0);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (2,4,11,23,'What is Python really?',0);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (3,5,15,26,'Which algorithm is the most efficient for sorting?',0);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (6,6,20,30,'How to build an AI?',1);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (8,7,17,23,'What is the difference between MongoDB and Mysql? ',1);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (2,8,11,22,'What advantages does Python have?',1);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (1,9,5,25,'How can I make a perfect app with JAVA?',1);
INSERT INTO `Questions` (`CourseId`,`QuestionLineId`,`StudentId`,`FacultyId`,`Question`,`VisibilityFlag`) VALUES (10,10,8,26,'What can I do to avoid bugs?',1);

INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (1,1);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (1,9);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (4,4);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (4,8);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (7,3);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (7,5);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (9,5);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (19,6);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (26,7);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (32,2);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (36,10);
INSERT INTO `Course-Questions` (`Materialid`,`QuestionLineId`) VALUES (37,10);


INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (1,'Algorithms');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (1,'SQL');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (2,'Algorithms');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (2,'SQL');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (3,'Java');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (4,'MongoDB');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (5,'Algorithms');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (5,'Python');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (6,'Algorithms');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (6,'Python');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (6,'Data');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (7,'Data');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (8,'SQL');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (9,'PHP');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (9,'JavaScript');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (10,'HTML');
INSERT INTO `SecondaryTopics` (`CourseId`,`TopicName`) VALUES (10,'PHP');

INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (1,1);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (1,2);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (1,4);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (1,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (1,3);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (1,6);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (1,9);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (2,10);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (2,1);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (2,2);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (3,4);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (3,3);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (3,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (3,7);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (3,9);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (4,3);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (4,4);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (4,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (5,1);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (5,2);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (6,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (6,8);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (6,10);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (7,8);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (7,9);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (7,10);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (8,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (8,6);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (8,9);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (9,3);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (9,4);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (9,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (10,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (10,7);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (11,2);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (11,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (12,3);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (12,6);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (12,7);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (13,3);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (13,6);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (13,8);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (14,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (15,6);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (15,8);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (15,10);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (16,2);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (16,7);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (17,2);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (17,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (18,1);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (18,3);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (18,4);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (18,7);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (19,6);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (20,5);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (20,7);
INSERT INTO `Student-Interest` (`StudentId`,`CourseId`) VALUES (20,10);


INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (1,2);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (1,3);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (1,6);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (1,8);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (2,15);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (2,1);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (3,3);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (3,4);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (3,7);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (3,9);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (3,15);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (3,16);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (4,5);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (4,8);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (5,11);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (5,17);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (5,20);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (5,19);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (5,7);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (5,8);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (6,6);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (6,3);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (6,2);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (6,4);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (6,8);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (6,15);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (7,17);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (7,19);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (7,18);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (8,3);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (8,4);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (8,5);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (8,6);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (8,9);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (9,15);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (9,16);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (9,1);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (9,3);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,2);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,8);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,13);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,14);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,15);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,4);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,5);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,6);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,7);
INSERT INTO `QuestionRating` (`QuestionLineId`,`LikedById`) VALUES (10,9);




